url/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.newuri, name='newuri'),
    url(r'^(?P<urlpk>\w{32})', views.geturi, name='geturi'), 


]

urlshort/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'urlshort.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('url.urls')),

]

url/models.py
from django.db import models
import uuid
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _

# Create your models here.

class Url(models.Model):
    url=        models.URLField(max_length=1000, verbose_name=_("Url:"), help_text=_('Introduce una url para acortar.'))
    shorturl=   models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date=       models.DateField(auto_now_add=True)

class UrlForm(ModelForm):
    class Meta:
        model=Url
        fields = ['url',]
        

url/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_http_methods
from django.http import HttpResponseRedirect, HttpResponse

from .models import UrlForm, Url

import uuid
from django.utils.translation import ugettext as _

# Create your views here.

@require_http_methods(["GET", "POST"])
def newuri(request):
    """
        Muestra el formulario para introducir la url
        y retorna la url acortada.
    """
    shorturl=None

    if request.method == 'POST':
        form = UrlForm(request.POST)
        if form.is_valid():
            # Se guarda y se devuelve la Url
            obj=form.save()
            shorturl=obj.shorturl.hex
            
            # Se limpia el form por si se desea arcortar más urls
            form=UrlForm()

    else:
        form = UrlForm()

    return render(request, 'url.html', {'shorturl':shorturl, 'form':form} )


@require_http_methods(["GET",])
def geturi(request, urlpk):
    """
        Expande la url
    """
    uri=get_object_or_404(Url, shorturl=uuid.UUID(urlpk))
    return HttpResponseRedirect(uri.url)

templates/main.html
{% load staticfiles %}
<html>
  <head>

    <title>
      {% block title %}{% endblock %}
    </title>

    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}" />   
    <link href='http://fonts.googleapis.com/css?family=Mrs+Sheppards' rel='stylesheet' type='text/css'>
  </head>

  <body>

<div id="main">
    <div id="header">
      {% block header %}{% endblock %}  
    </div>

    <div id="content">
     <center> <div id="logo"><img class="logo" src="{% static 'logo.png' %}"></div></center>
      {% block content %}{% endblock %}
    </div>

    <div id="footer">
      {% block footer %}{% endblock %}
    </div>
</div>
  </body>

</html>

templates/url.html
{% extends "main.html" %}
{% load i18n %}

{% block title %}
{% trans 'Acortador de urls' %}
{% endblock %}

{% block header %}
<p align="center" id="title">{% trans 'ACORTADOR DE URLS' %}</p>
{% endblock %}

{% block content %}
<center><div id="form"> 
<form action="" method="post">
  
 
  {% csrf_token %}
  
  <label for="id_url">{{ form.url.label }}</label>
  {{ form.url }}

  <input type="submit" id="submit" value="{% trans 'Acortar!' %}"/>
  <label class="helptext">{{ form.url.help_text }}</label>
  <div class="errorlist">{{ form.url.error_list }}</div>
</form>
</div></center>

{% endblock %}


{% block footer %}
  {% if shorturl %}

  	<center><span>{% trans 'Url acortada:' %}</br>
	<a href="{% url 'geturi' shorturl %}">{% url 'geturi' shorturl %}</a>
  	</span></center>
  	<span>{{ fecha }}</span>
  	
  {% endif %}
{% endblock %}